apiVersion: "v1"
kind: "Service"
metadata:
  name: "frontend-service"
  namespace: "default"
  labels:
    app: "react-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "react-app"
  type: "LoadBalancer"
  loadBalancerIP: ""




